<?php

class IncidentForm
{
	public static $branches = array(
		''                   => '--',
		'Association Office' => 'Association Office',
		'Camp Campbell'		 => 'Camp Campbell',
		'Central' 			 => 'Central',
		'East Palo Alto' 	 => 'East Palo Alto',
		'East Valley' 		 => 'East Valley',
		'El Camino' 		 => 'El Camino',
		'Mt Madonna'         => 'Mt Madonna',
		'Northwest' 		 => 'Northwest',
		'Page Mill' 		 => 'Page Mill',
		'Palo Alto' 		 => 'Palo Alto',
		'Sequoia' 		     => 'Sequoia',
		'South Valley' 		 => 'South Valley',
		'Southwest' 		 => 'Southwest'
	);

	public static $offSiteLocations = array(
		'' => '--',
		'CN - Booksin' => 'CN - Booksin',
		'CN - Bowers' => 'CN - Bowers',
		'CN - Bracher' => 'CN - Bracher',
		'CN - Briarwood' => 'CN - Briarwood',
		'CN - Buchser Middle' => 'CN - Buchser Middle',
		'CN - Cabrillo Middle' => 'CN - Cabrillo Middle',
		'CN - CW Haman' => 'CN - CW Haman',
		'CN - Don Callejon' => 'CN - Don Callejon',
		'CN - Galarza-Hammer' => 'CN - Galarza-Hammer',
		'CN - Hughes' => 'CN - Hughes',
		'CN - Montague' => 'CN - Montague',
		'CN - Pomeroy' => 'CN - Pomeroy',
		'CN - Rocketship Alma' => 'CN - Rocketship Alma',
		'CN - Rocketship Discovery' => 'CN - Rocketship Discovery',
		'CN - Rocketship Los Suenos' => 'CN - Rocketship Los Suenos',
		'CN - Rocketship Mateo Sheedy' => 'CN - Rocketship Mateo Sheedy',
		'CN - Rocketship Mosaic' => 'CN - Rocketship Mosaic',
		'CN - Rocketship Si Se Puede' => 'CN - Rocketship Si Se Puede',
		'CN - Scott Lane' => 'CN - Scott Lane',
		'EC - Almond' => 'EC - Almond',
		'EC - Bubb' => 'EC - Bubb',
		'EC - Castro' => 'EC - Castro',
		'EC - Huff' => 'EC - Huff',
		'EC - Landels' => 'EC - Landels',
		'EC - Landels Preschool' => 'EC - Landels Preschool',
		'EC - Monta Loma' => 'EC - Monta Loma',
		'EC - Oak' => 'EC - Oak',
		'EC - Oak Preschool' => 'EC - Oak Preschool',
		'EC - Theurakauf ' => 'EC - Theurakauf ',
		'EV - BYC' => 'EC - Theurakauf ',
		'EV - Carolyn Clark' => 'EV - Carolyn Clark',
		'EV - Cassell' => 'EV - Cassell',
		'EV - Dove Hill' => 'EV - Dove Hill',
		'EV - East Valley Preschool' => 'EV - East Valley Preschool',
		'EV - J. F. Smith' => 'EV - J. F. Smith',
		'EV - KR Smith' => 'EV - KR Smith',
		'EV - LeyVa' => 'EV - LeyVa',
		'EV - Linda Vista' => 'EV - Linda Vista',
		'EV - LUCHA' => 'EV - LUCHA',
		'EV - Montgomery' => 'EV - Montgomery',
		'EV - Northwood' => 'EV - Northwood',
		'EV - O.B. Whaley' => 'EV - O.B. Whaley',
		'EV - Pomeroy' => 'EV - Pomeroy',
		'EV - Randall' => 'EV - Randall',
		'EV - Rogers' => 'EV - Rogers',
		'EV - Rose' => 'EV - Rose',
		'EV - Russo-McEntee' => 'EV - Russo-McEntee',
		'EV - Ryan' => 'EV - Ryan',
		'EV - San Antonio' => 'EV - San Antonio',
		'EV - Silver Oak' => 'EV - Silver Oak',
		'EV - Toyon' => 'EV - Toyon',
		'EV - Vinci Park AS' => 'EV - Vinci Park AS',
		'MM - Antonio Del Buono' => 'MM - Antonio Del Buono',
		'MM - Barrett' => 'MM - Barrett',
		'MM - Barrett CC' => 'MM - Barrett CC',
		'MM - Brownell Middle' => 'MM - Brownell Middle',
		'MM - El Roble' => 'MM - El Roble',
		'MM - Jackson' => 'MM - Jackson',
		'MM - Las Animas' => 'MM - Las Animas',
		'MM - Luigi Aprea' => 'MM - Luigi Aprea',
		'MM - Morgan Hill Charter' => 'MM - Morgan Hill Charter',
		'MM - PA Walsh' => 'MM - PA Walsh',
		'MM - Paradise Valley' => 'MM - Paradise Valley',
		'MM - Paradise Valley Preschool' => 'MM - Paradise Valley Preschool',
		'MM - Rucker' => 'MM - Rucker',
		'MM - San Martin/Gwinn' => 'MM - San Martin/Gwinn',
		'NW - Bishop' => 'NW - Bishop',
		'NW - Blue Hills' => 'NW - Blue Hills',
		'NW - Christa McAuliffe' => 'NW - Christa McAuliffe',
		'NW - Columbia Middle' => 'NW - Columbia Middle',
		'NW - Eisenhower' => 'NW - Eisenhower',
		'NW - Ellis' => 'NW - Ellis',
		'NW - Fairwood' => 'NW - Fairwood',
		'NW - Hyde Middle' => 'NW - Hyde Middle',
		'NW - Lakewood' => 'NW - Lakewood',
		'NW - Lakewood' => 'NW - Lakewood',
		'NW - Lakewood Preschool' => 'NW - Lakewood Preschool',
		'NW - Lincoln' => 'NW - Lincoln',
		'NW - Magnolia Science Academy' => 'NW - Magnolia Science Academy',
		'NW - Meyerholz' => 'NW - Meyerholz',
		'NW - Muir' => 'NW - Muir',
		'NW - San Miguel' => 'NW - San Miguel',
		'NW - Stevens Creek' => 'NW - Stevens Creek',
		'NW - Vargas' => 'NW - Vargas',
		'NW - West Valley' => 'NW - West Valley',
		'RW - Adelante' => 'RW - Adelante',
		'RW - Boulder Creek' => 'RW - Boulder Creek',
		'RW - Roosevelt' => 'RW - Roosevelt',
		'SV - Allen at Steinbeck' => 'SV - Allen at Steinbeck',
		'SV - Almaden' => 'SV - Almaden',
		'SV - Del Roble' => 'SV - Del Roble',
		'SV - Hacienda' => 'SV - Hacienda',
		'SV - Los Paseos' => 'SV - Los Paseos',
		'SV - Oak Ridge' => 'SV - Oak Ridge',
		'SV - Reed' => 'SV - Reed',
		'SV - Sakamoto' => 'SV - Sakamoto',
		'SV - Schallenberger' => 'SV - Schallenberger',
		'SV - Schallenberger Preschool' => 'SV - Schallenberger Preschool',
		'SV - Simonds' => 'SV - Simonds',
		'SV - Terrell' => 'SV - Terrell',
		'SV - Terrell Child Care' => 'SV - Terrell Child Care',
		'SW - Anderson' => 'SW - Anderson',
		'SW - Discovery Charter' => 'SW - Discovery Charter',
		'SW - Fammatre' => 'SW - Fammatre',
		'SW - Farnham' => 'SW - Farnham'
	);

	public static $locations = array(
		'' => '--',
		'Pool' => 'Pool',
		'Gym' => 'Gym',
		'Lobby' => 'Lobby',
		'Parking Lot' => 'Parking Lot',
		'Bathroom' => 'Bathroom', 
		'Special Needs Bathroom' => 'Special Needs Bathroom', 
		'Locker Room' => 'Locker Room', 
		'Hallway' => 'Hallway',
		'Playground'=>'Playground',
		'Cafeteria'=>'Cafeteria',
		'Classroom'=>'Classroom',
		'Field'=>'Field'
	);

	public static $involvement = array(
		'' => '--',
		'Member' => 'Member',
		'Participant' => 'Participant',
		'Volunteer' => 'Volunteer',
		'Staff' => 'Staff'
	);

	public static $gender = array(
		'' => '--',
		'Male' => 'Male',
		'Female' => 'Female',
		'Unknown' => 'Unknown'
	);

	public static $status = array(
		'' => '--',
		'Open' => 'Open',
		'Branch Approved' => 'Branch Approved',
		'Risk Approved' => 'Risk Approved',
		'Sent To Insurance' => 'Sent To Insurance',
		'Resolved' => 'Resolved',
		'Pending'=>'Pending',
		'Reviewed by Branch'=>'Reviewed by Branch',
		'Reviewed by Risk'=>'Reviewed by Risk',
		'Submitted to Insurance'=>'Submitted to Insurance',
		'Closed'=>'Closed'
	);

	public static $witnessType = array(
		'' => '--',
		'Witness' => 'Witness',
		'Responder' => 'Responder'
	);
	public static $report = array(
		'' => '--',
		'Do Not Report' => 'Do Not Report',
		'Report' => 'Report',
		'Claim'=>'Claim'
	);
}